Adjust test to remove dependency on mysqli - to avoid need for this being installed on CI server

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,7 +24,6 @@ jobs:
         uses: shivammathur/setup-php@v2
         with:
           php-version: 7.3
-          extensions: mysqlnd, mysqli
           tools: psalm
 
       - name: Validate composer.json and composer.lock
@@ -42,10 +41,6 @@ jobs:
       - name: Install dependencies
         run: composer install --prefer-dist --no-progress
 
-      # Note, lint errors are being escaped here - so this will report, but not cause the build to fail
-      - name: Run Psalm
-        run: psalm --output-format=github || exit 0
-
       - name: PHPUnit Tests
         uses: php-actions/phpunit@v3
         env:
@@ -56,6 +51,10 @@ jobs:
           php_extensions: xdebug
           args: --coverage-text
           php_version: 7.3
+
+      # Note, lint errors are being escaped here - so this will report, but not cause the build to fail
+      - name: Run Psalm
+        run: psalm --output-format=github || exit 0
 
   js_build:
     name: JavaScript build, test and lint
